### PR TITLE
Replace Python usage of removed getargspec with getfullargspec

### PR DESCRIPTION
**Pull request by tcitworld**
getargspec is removed in Python 3.11 and was depreciated since Python 3

### CODE REVIEW

**Comment by lessless** [comment]
I got bitten by this today! Thanks for the PR @tcitworld

**Review by l9kd1 — DISMISSED** [review]

**Comment by Nimond** [comment]
You can't do this just replacing func name, [`inspect.getfullargspec`](https://docs.python.org/3.10/library/inspect.html#inspect.getfullargspec) returns tuple of 7 elements, not 4
Valid fix:
```python
args, varargs, _keywords, defaults, _kwonlyargs, _kwonlydefaults, _annotations = getfullargspec(handler)
# or
args, varargs, _keywords, defaults, *_rest = getfullargspec(handler)
```

File: priv/python3/erlport/erlang.py [hunk 1]
```diff
@@ -127,8 +127,8 @@ def set_message_handler(self, handler):
         self.handler = handler
 
     def _check_handler(self, handler):
-        # getargspec will raise TypeError if handler is not a function
-        args, varargs, _keywords, defaults = getargspec(handler)
+        # getfullargspec will raise TypeError if handler is not a function
+        args, varargs, _keywords, defaults = getfullargspec(handler)
```
Comment (Dnomin) [inline priv/python3/erlport/erlang.py]: You can't do this just replacing func name, [`inspect.getfullargspec`](https://docs.python.org/3.10/library/inspect.html#inspect.getfullargspec) returns tuple of 7 elements, not 4
Valid fix:
```python
args, varargs, _keywords, defaults, _kwonlyargs, _kwonlydefaults, _annotations = getfullargspec(handler)
# or
args, varargs, _keywords, defaults, *_rest = getfullargspec(handler)
```

**Review by Dnomin — CHANGES_REQUESTED** [review]

File: priv/python3/erlport/erlang.py (hunk 1 above)
Comment (tcitworld) [reply priv/python3/erlport/erlang.py]: Fixed, thanks. :see_no_evil:

**Review by Dnomin — APPROVED** [review]

**Comment by dennym** [comment]
Just stumbled on this and prepped to get it into upstream and the only thing left to do for me is to hail you a big thank you

🥇

**Comment by lessless** [comment]
@l9kd1 @dennym it will be really appreciated if you can merge this ASAP

**Comment by lessless** [comment]
@tcitworld by the way, would that work with the changes in Python 3.11 that you mentioned in https://github.com/hdima/erlport/issues/60?

**Comment by dennym** [comment]
Unfortunately I do not have stakes in this repository. I just had the same issue and stumbled upon your PR and wanted to give my appreciation. Currently I pull the hex package straight from git.

**Comment by lessless** [comment]
cc @filmor @feng19

**Review by feng19 — APPROVED** [review]

**Comment by lessless** [comment]
thank you @feng19 🎉

are you going to cut a release?

**Comment by feng19** [comment]
release https://hex.pm/packages/erlport/0.11.0
